In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [4]:
a = 'the Sun of beach and beach'
b = 'moon earth moon'

In [6]:
text = [a, b]

tfv = TfidfVectorizer(stop_words='english')
matrix = tfv.fit_transform(text)
print(tfv.get_feature_names())
print(matrix.toarray().round(3))

['beach', 'earth', 'moon', 'sun']
[[0.894 0.    0.    0.447]
 [0.    0.447 0.894 0.   ]]


In [7]:
import pandas as pd

matrix = matrix.todense()
df = pd.DataFrame(matrix, columns=tfv.get_feature_names(), index=['a', 'b'])
df.round(3)

/Users/apple/opt/anaconda3/envs/opencv/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


beach  earth   moon    sun
a  0.894  0.000  0.000  0.447
b  0.000  0.447  0.894  0.000

In [9]:
a = 'the Sun of beach and beach'
b = 'moon earth moon'

text = [a, b]

tfv = TfidfVectorizer()
matrix = tfv.fit_transform(text)
print(tfv.get_feature_names())
print(matrix.toarray().round(3))

['and', 'beach', 'earth', 'moon', 'of', 'sun', 'the']
[[0.354 0.707 0.    0.    0.354 0.354 0.354]
 [0.    0.    0.447 0.894 0.    0.    0.   ]]


In [10]:
import pandas as pd

matrix = matrix.todense()
df = pd.DataFrame(matrix, columns=tfv.get_feature_names(), index=['a', 'b'])
df.round(3)

and  beach  earth   moon     of    sun    the
a  0.354  0.707  0.000  0.000  0.354  0.354  0.354
b  0.000  0.000  0.447  0.894  0.000  0.000  0.000

In [11]:
#workshop 2

In [16]:
a = 'the Sun of beach and beach'
b = 'moon earth moon'
c = 'the sun is an object in the sky'
d = '...'

text = [a, b, c, d]
tfv = TfidfVectorizer()
matrix = tfv.fit_transform(text)
print(tfv.get_feature_names())
print(matrix.toarray().round(3))
matrix = matrix.todense()
df = pd.DataFrame(matrix, columns=tfv.get_feature_names(), index=['a', 'b', 'c', 'd'])
df.round(3)

['an', 'and', 'beach', 'earth', 'in', 'is', 'moon', 'object', 'of', 'sky', 'sun', 'the']
[[0.    0.372 0.743 0.    0.    0.    0.    0.    0.372 0.    0.293 0.293]
 [0.    0.    0.    0.447 0.    0.    0.894 0.    0.    0.    0.    0.   ]
 [0.351 0.    0.    0.    0.351 0.351 0.    0.351 0.    0.351 0.277 0.554]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   ]]


an    and  beach  earth     in     is   moon  object     of    sky  \
a  0.000  0.372  0.743  0.000  0.000  0.000  0.000   0.000  0.372  0.000   
b  0.000  0.000  0.000  0.447  0.000  0.000  0.894   0.000  0.000  0.000   
c  0.351  0.000  0.000  0.000  0.351  0.351  0.000   0.351  0.000  0.351   
d  0.000  0.000  0.000  0.000  0.000  0.000  0.000   0.000  0.000  0.000   

     sun    the  
a  0.293  0.293  
b  0.000  0.000  
c  0.277  0.554  
d  0.000  0.000