In [10]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [11]:
a = 'beach sea beach'
b = 'Beach sea sea Beach beach beach'

In [12]:
text = [a, b]
cv = CountVectorizer()
count_matrix = cv.fit_transform(text)

print(cv.get_feature_names())
print(count_matrix.toarray())

['beach', 'sea']
[[2 1]
 [4 2]]


In [13]:
term_matrix = count_matrix.todense()
df = pd.DataFrame(term_matrix, columns=cv.get_feature_names(), index=['a', 'b'])

df

beach  sea
a      2    1
b      4    2

In [14]:
cosine_sim = cosine_similarity(count_matrix)
cosine_sim

array([[1., 1.],
       [1., 1.]])

In [15]:
#workshop 2

In [16]:
a = 'blue skirt dress lady'
b = 'blue shirt lady'
c = 'smartphone android'
d = 'charger smartphone tablet'

text = [a, b, c, d]

cv = CountVectorizer()
count_matrix = cv.fit_transform(text)

term_matrix = count_matrix.todense()

df = pd.DataFrame(term_matrix, columns=cv.get_feature_names(), index=['a', 'b', 'c', 'd'])
df

android  blue  charger  dress  lady  shirt  skirt  smartphone  tablet
a        0     1        0      1     1      0      1           0       0
b        0     1        0      0     1      1      0           0       0
c        1     0        0      0     0      0      0           1       0
d        0     0        1      0     0      0      0           1       1

In [17]:
cosine_sim = cosine_similarity(count_matrix)
cosine_sim

array([[1.        , 0.57735027, 0.        , 0.        ],
       [0.57735027, 1.        , 0.        , 0.        ],
       [0.        , 0.        , 1.        , 0.40824829],
       [0.        , 0.        , 0.40824829, 1.        ]])

In [19]:
ref_index = 2
similar_score = cosine_sim[ref_index]
similar_score.round(2)

array([0.  , 0.  , 1.  , 0.41])

In [20]:
#workshop 3

In [21]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [22]:
df = pd.read_csv('./csv/movie.csv')
df

index     budget                                    genres  \
0         0  237000000  Action Adventure Fantasy Science Fiction   
1         1  300000000                  Adventure Fantasy Action   
2         2  245000000                    Action Adventure Crime   
3         3  250000000               Action Crime Drama Thriller   
4         4  260000000          Action Adventure Science Fiction   
...     ...        ...                                       ...   
4798   4798     220000                     Action Crime Thriller   
4799   4799       9000                            Comedy Romance   
4800   4800          0             Comedy Drama Romance TV Movie   
4801   4801          0                                       NaN   
4802   4802          0                               Documentary   

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995   
1          http://disney.go.com/disneypictures/pirates/     285   
2           http://www.sonypictures.com/movies/spectre/  206647   
3                    http://www.thedarkknightrises.com/   49026   
4                  http://movies.disney.com/john-carter   49529   
...                                                 ...     ...   
4798                                                NaN    9367   
4799                                                NaN   72766   
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4801                        http://shanghaicalling.com/  126186   
4802                                                NaN   25975   

                                               keywords original_language  \
0     culture clash future space war space colony so...                en   
1     ocean drug abuse exotic island east india trad...                en   
2            spy based on novel secret agent sequel mi6                en   
3     dc comics crime fighter terrorist secret ident...                en   
4     based on novel mars medallion space travel pri...                en   
...                                                 ...               ...   
4798  united states\u2013mexico barrier legs arms pa...                es   
4799                                                NaN                en   
4800  date love at first sight narration investigati...                en   
4801                                                NaN                en   
4802               obsession camcorder crush dream girl                en   

                                original_title  \
0                                       Avatar   
1     Pirates of the Caribbean: At World's End   
2                                      Spectre   
3                        The Dark Knight Rises   
4                                  John Carter   
...                                        ...   
4798                               El Mariachi   
4799                                 Newlyweds   
4800                 Signed, Sealed, Delivered   
4801                          Shanghai Calling   
4802                         My Date with Drew   

                                               overview  popularity  ...  \
0     In the 22nd century, a paraplegic Marine is di...  150.437577  ...   
1     Captain Barbossa, long believed to be dead, ha...  139.082615  ...   
2     A cryptic message from Bond’s past sends him o...  107.376788  ...   
3     Following the death of District Attorney Harve...  112.312950  ...   
4     John Carter is a war-weary, former military ca...   43.926995  ...   
...                                                 ...         ...  ...   
4798  El Mariachi just wants to play his guitar and ...   14.269792  ...   
4799  A newlywed couple's honeymoon is upended by th...    0.642552  ...   
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476  ...   
4801  When ambitious New York attorney Sam is sent t...    0.857008  ...   
4802  Ever since the s

In [23]:
df.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [24]:
df.isnull().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [25]:
df[df['title'].str.contains('transformer', case=False)]['title']

35     Transformers: Revenge of the Fallen
36         Transformers: Age of Extinction
52          Transformers: Dark of the Moon
111                           Transformers
Name: title, dtype: object

In [26]:
df.iloc[111]['overview']

'Young teenager, Sam Witwicky becomes involved in the ancient struggle between two extraterrestrial factions of transforming robots – the heroic Autobots and the evil Decepticons. Sam holds the clue to unimaginable power and the Decepticons will stop at nothing to retrieve it.'

In [28]:
df.iloc[111]['keywords']

'destroy transformation alien based on toy transformers'

In [32]:
feature = ['keywords', 'cast', 'genres', 'director']
# df[feature].isnull().sum()
df[feature]

keywords  \
0     culture clash future space war space colony so...   
1     ocean drug abuse exotic island east india trad...   
2            spy based on novel secret agent sequel mi6   
3     dc comics crime fighter terrorist secret ident...   
4     based on novel mars medallion space travel pri...   
...                                                 ...   
4798  united states\u2013mexico barrier legs arms pa...   
4799                                                NaN   
4800  date love at first sight narration investigati...   
4801                                                NaN   
4802               obsession camcorder crush dream girl   

                                                   cast  \
0     Sam Worthington Zoe Saldana Sigourney Weaver S...   
1     Johnny Depp Orlando Bloom Keira Knightley Stel...   
2     Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3     Christian Bale Michael Caine Gary Oldman Anne ...   
4     Taylor Kitsch Lynn Collins Samantha Morton Wil...   
...                                                 ...   
4798  Carlos Gallardo Jaime de Hoyos Peter Marquardt...   
4799  Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...   
4800  Eric Mabius Kristin Booth Crystal Lowe Geoff G...   
4801  Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...   
4802  Drew Barrymore Brian Herzlinger Corey Feldman ...   

                                        genres           director  
0     Action Adventure Fantasy Science Fiction      James Cameron  
1                     Adventure Fantasy Action     Gore Verbinski  
2                       Action Adventure Crime         Sam Mendes  
3                  Action Crime Drama Thriller  Christopher Nolan  
4             Action Adventure Science Fiction     Andrew Stanton  
...                                        ...                ...  
4798                     Action Crime Thriller   Robert Rodriguez  
4799                            Comedy Romance       Edward Burns  
4800             Comedy Drama Romance TV Movie        Scott Smith  
4801                                       NaN        Daniel Hsia  
4802                               Documentary   Brian Herzlinger  

[4803 rows x 4 columns]

In [33]:
df[feature] = df[feature].fillna('')

In [34]:
df[feature].isnull().sum()

keywords    0
cast        0
genres      0
director    0
dtype: int64

In [35]:
df['combined_feature'] = df['keywords'] + ' ' + df['cast'] + ' ' + df['genres'] + ' ' + df['director']

In [36]:
df['combined_feature']

0       culture clash future space war space colony so...
1       ocean drug abuse exotic island east india trad...
2       spy based on novel secret agent sequel mi6 Dan...
3       dc comics crime fighter terrorist secret ident...
4       based on novel mars medallion space travel pri...
                              ...                        
4798    united states\u2013mexico barrier legs arms pa...
4799     Edward Burns Kerry Bish\u00e9 Marsha Dietlein...
4800    date love at first sight narration investigati...
4801     Daniel Henney Eliza Coupe Bill Paxton Alan Ru...
4802    obsession camcorder crush dream girl Drew Barr...
Name: combined_feature, Length: 4803, dtype: object

In [37]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df['combined_feature'])
count_matrix.shape

(4803, 14845)

In [40]:
print(cv.get_feature_names()[:10])
print(cv.get_feature_names()[-10:])

['11', '15th', '17th', '18th', '1910s', '1917', '1920s', '1930s', '1950s', '1960s']
['zuehlsdorff', 'zukovic', 'zuleikha', 'zuniga', 'zurer', 'zvyagintsev', 'zwart', 'zwick', 'zwigoff', 'zylka']


In [42]:
print(count_matrix.toarray()[:10, 10:30])

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [44]:
cosine_sim = cosine_similarity(count_matrix)
cosine_sim.shape

(4803, 4803)

In [45]:
print(cosine_sim[:8, :8].round(3))

[[1.    0.105 0.12  0.038 0.231 0.192 0.    0.141]
 [0.105 1.    0.076 0.036 0.073 0.256 0.    0.067]
 [0.12  0.076 1.    0.164 0.209 0.125 0.    0.19 ]
 [0.038 0.036 0.164 1.    0.039 0.078 0.    0.036]
 [0.231 0.073 0.209 0.039 1.    0.2   0.    0.219]
 [0.192 0.256 0.125 0.078 0.2   1.    0.    0.073]
 [0.    0.    0.    0.    0.    0.    1.    0.   ]
 [0.141 0.067 0.19  0.036 0.219 0.073 0.    1.   ]]


In [89]:
user_choice = 'The Dark Knight Rises'
ref_index = df[df['title'].str.contains(user_choice, case=False)].index[0]

print('User choice ref_index = {}'.format(ref_index))

User choice ref_index = 3


In [90]:
similar_movies = [list(enumerate(cosine_sim[ref_index]))]
similar_movies[:8]

[[(0, 0.03774256780481986),
  (1, 0.03580574370197164),
  (2, 0.16357216402190616),
  (3, 0.9999999999999997),
  (4, 0.03922322702763681),
  (5, 0.07844645405527362),
  (6, 0.0),
  (7, 0.03580574370197164),
  (8, 0.08362420100070908),
  (9, 0.12009611535381537),
  (10, 0.11766968108291043),
  (11, 0.23533936216582085),
  (12, 0.04089304100547654),
  (13, 0.03922322702763681),
  (14, 0.14824986333222023),
  (15, 0.0),
  (16, 0.03522349768381735),
  (17, 0.04181210050035454),
  (18, 0.07161148740394328),
  (19, 0.04181210050035454),
  (20, 0.04003203845127179),
  (21, 0.04003203845127179),
  (22, 0.0),
  (23, 0.0),
  (24, 0.06933752452815364),
  (25, 0.08770580193070293),
  (26, 0.03706246583305506),
  (27, 0.08006407690254358),
  (28, 0.08006407690254358),
  (29, 0.1254363015010636),
  (30, 0.07692307692307693),
  (31, 0.07844645405527362),
  (32, 0.07412493166611012),
  (33, 0.07412493166611012),
  (34, 0.0),
  (35, 0.08559209850218259),
  (36, 0.08006407690254358),
  (37, 0.0),
  (38,

In [96]:
sorted_similar_movies = sorted(similar_movies[0][1:], key=lambda x:x[1], reverse=True)
sorted_similar_movies[:6]

[(3, 0.9999999999999997),
 (119, 0.7307692307692306),
 (65, 0.6923076923076922),
 (4638, 0.45291081365783836),
 (2793, 0.39467610868816316),
 (1196, 0.37630890450319093)]

In [97]:
df['title'][119]

'Batman Begins'

In [98]:
print('Recommend movies for [' + user_choice + ']')
print('-------------------------------------------')

for i, element in enumerate(sorted_similar_movies):
    similar_movies_id = element[0]
    similar_movies_title = df['title'].iloc[similar_movies_id]
    s_score = element[1]
    print('{:30} -> {:.3f}'.format(similar_movies_title, s_score))
    if i > 6:
        break

Recommend movies for [The Dark Knight Rises]
-------------------------------------------
The Dark Knight Rises          -> 1.000
Batman Begins                  -> 0.731
The Dark Knight                -> 0.692
Amidst the Devil's Wings       -> 0.453
The Killer Inside Me           -> 0.395
The Prestige                   -> 0.376
Batman Returns                 -> 0.360
Batman                         -> 0.353
